#Date: 2023-04-02
#Author: Tony
#Description:
#Create EC2 instance using region mapping

Mappings:
  RegionMap:
    cn-north-1:
      AMI: ami-0e82057f7434f0542
    cn-northwest-1:
      AMI: ami-0ea68e9c2835c8288

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId:
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      Tags:
        - Key: Name
          Value: !Join [ ":", [ Web, Server01 ] ]
