#Date: 2023-04-02
#Author: Tony
#Description:
#A simple script to create EC2 instance.

Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0e82057f7434f0542
      Tags:
        - Key: Name
          Value: Web01
